added functions to new script, kept old for reference
jfergii/python pull request #1
Opened 2020-10-29 16:01 UTC by jfergii

Added new file to do functions in and I kept the old for reference. I know that's not standard since I would be merging to master.

2020-10-30 17:25 UTC, GeekTeaa commented
For a rule of thumb, all your functions should be no more that 10 lines long

2020-10-30 22:17 UTC, GeekTeaa requested changes

2020-10-30 22:17 UTC, GeekTeaa commented on guessTheNumber.py
> +#while loop for attempt limit - not sure if this could be done better
Everything can be done better, but things are often "Good enough." Try to avoid going to deep into a "Can this be done better" mindset. Sometimes, its important, but most of the time its a slippery slope to wasted time. The only time I think you should be diving into the "Is this good enough" line of think is if you don't feel the logic is clear to another programmer trying to read your code.

2020-10-30 22:17 UTC, GeekTeaa commented on guessTheNumber.py
> +        sys.exit()  #are these proper exits?
Yes! The scope of this program is very short, so absolutely. If we're talking bigger projects, there are good reasons to encapsulate this in an exit function of your own. All your coding decisions should be proportional to the environment you're coding for.

2020-10-30 22:17 UTC, GeekTeaa commented on guessTheNumber.py
> +#not sure if i can end the program  in a better way
This is fine

2020-10-30 22:17 UTC, GeekTeaa commented on guessTheNumberFunctions.py
> +#main function - is this the preferred way in python to declare main?
For a better explanation on how this is done, I recommend using this https://www.youtube.com/watch?v=lOeIDvyRUQs
Its a good video, and really showcases how this best practice benefits a program. Its quite powerful when used properly.

2020-10-30 22:17 UTC, GeekTeaa commented on guessTheNumberFunctions.py
> +    #imports for function
There are cases where you should do import while in a function, but I wouldn't do it anywhere else but at the beginning of the file while you're learning Python.

2020-10-30 22:17 UTC, GeekTeaa commented on guessTheNumberFunctions.py
> +def Main():
Do your naming conventions meet pip8?

2020-10-30 22:17 UTC, GeekTeaa commented on guessTheNumberFunctions.py
> +    def playGame():
You have a comment at each block of logic in `playGame`. For each of these comments, you could have had a function instead. Use functions to explain your logic, your code will become more self-explanatory in the process. I personally see comments as a "necessary evil". You need them because we as humans don't write perfect code (i.e. code that instantly make sense to all readers). But, each time you write a comment to explain your code, stop yourself and ask "Could I have written this code differently so I wouldn't need this comment?". The answer is often "Yes."

Note: The answer can also be "Yes! But its good enough and I need to move on!"

2020-10-30 22:17 UTC, GeekTeaa commented on guessTheNumberFunctions.py
> +        print("Would you like to play the number game? yes/no")
Strings are clunky objects to be using for validation. So, its best to encapsulate all your string handling in one function, then return an object that is easier to use through the rest of your software. Heres an example of how I would have written this function. 

```py
"""
This makes any response besides 'yes' a failure. 
This may not be desirable, and it is a change of 
functionality from what you had written. 
I would handle that case using more advanced coding 
logic that I don't want to cover at this stage.
"""
def promptUserToPlayGame():
  print("Would you like to play the number game? Type yes to continue.")
  yesNo = userInput()
  return yesNo == "yes" # This returns a boolean

def promptUser():
  play = promptUserToPlayGame()
  if play:
    print("Great! Lets continue...")
  else:
    print("Maybe next time!")
    sysexit()
```
Then in `playGame()` you just call...
```py
  promptUser()
```

2020-10-30 22:17 UTC, GeekTeaa commented on guessTheNumberFunctions.py
> +        print("Would you like to play the number game? yes/no")
This does a lot for your programmers. One, the internals of `promptUser()` make a lot of sense to a reader at a glance. Two, you encapsulate all string manipulation to one place at `promptUserToPlayGame()`. If you wanted to change how that is done, or change 'yes' to something else, its a change in place and the rest of the code is totally safe. This means your code is more maintainable.

2020-10-30 22:17 UTC, GeekTeaa commented on guessTheNumberFunctions.py
> +        print("Would you like to play the number game? yes/no")
It does a lot more, but I won't cover that stuff yet. Just absorb this for now.

2020-11-02 18:02 UTC, closed without merging

2020-11-02 18:02 UTC, jfergii commented
Refactored, making new pull request